Repository IMAP-Science-Operations-Center/sds-data-manager, pull requests merged in 2023-12, with the labels that each got.

#201 CI: Remove version pin on npm cdk version installation
  .github/workflows/deploy.yml
Labels: deployment

#200 Setup Personal AWS Deploy Documentation
  docs/source/cdk/cdk-deployment-personal-aws.rst
  docs/source/cdk/index.rst
Labels: documentation

#205 Added some more info to personal AWS account docs
  docs/source/cdk/cdk-deployment-personal-aws.rst
Labels: documentation

#206 ENH: Add redirect response from download url
  sds_data_manager/lambda_code/SDSCode/download_query_api.py
  tests/lambda_endpoints/test_download_query_api.py
Labels: enhancement
