Repository IMAP-Science-Operations-Center/sds-data-manager, pull requests merged in 2024-12, with the labels that each got.

#398 I-ALiRT: Add query api to s3 bucket
  sds_data_manager/constructs/ialirt_api_manager_construct.py
  sds_data_manager/constructs/lambda_layer_construct.py
  sds_data_manager/lambda_code/IAlirtCode/ialirt_query_api.py
  sds_data_manager/utils/stackbuilder.py
  tests/lambda_endpoints/test_ialirt_query_api.py
Labels: I-ALiRT

#409 BUG: Removing pytest-postgresql temporarily
  poetry.lock
  pyproject.toml
Labels: bug

#412 I-ALiRT: Domain Name Update
  sds_data_manager/constructs/api_gateway_construct.py
  sds_data_manager/utils/stackbuilder.py
Labels: I-ALiRT

#416 Dependency Association updates
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/batch_starter.py
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/dependency.py
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/dependency_config.csv
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/dependency_config.py
  tests/lambda_endpoints/test_batch_starter.py
  tests/lambda_endpoints/test_dependency.py
Labels: enhancement

#420 Adding monitoring to send clean logging emails
  sds_data_manager/constructs/indexer_lambda_construct.py
  sds_data_manager/constructs/monitoring_lambda_construct.py
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/monitoring.py
  sds_data_manager/utils/stackbuilder.py
  tests/infrastructure/test_indexer_lambda_construct.py
Labels: enhancement, Infrastructure

#415 I-ALiRT: Add Outbound Test
  tests/test-data/ialirt_ec2/Dockerfile
  tests/test-data/ialirt_ec2/test_app.py
Labels: I-ALiRT

#421 I-ALiRT: Added IP range for BlueNet (tlm relay)
  sds_data_manager/constructs/ialirt_processing_construct.py
Labels: I-ALiRT

#425 SWAPI dependency updates
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/dependency_config.csv
Labels: enhancement

#426 v5.0.0 Release
  pyproject.toml
Labels: Release
