Repository IMAP-Science-Operations-Center/sds-data-manager, pull requests merged in 2025-03, with the labels that each got.

#463 Upload lambda changes for Ancillary Support
  poetry.lock
  pyproject.toml
  sds_data_manager/lambda_code/SDSCode/api_lambdas/upload_api.py
  tests/lambda_endpoints/conftest.py
  tests/lambda_endpoints/test_upload_api.py
Labels: Student

#472 Fixing requirements.txt file for lambda
  lambda_layer/python/requirements.txt
  poetry.lock
Labels: bug

#486 IDEX l2a dependency
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/dependency_config.csv
Labels: Infrastructure
