Repository IMAP-Science-Operations-Center/sds-data-manager, pull requests merged in 2025-07, with the labels that each got.

#712 v7.0.0 Release
  pyproject.toml
Labels: Release

#721 BUG: SPICE fix from last PR
  sds_data_manager/constructs/indexer_lambda_construct.py
  sds_data_manager/constructs/sds_api_manager_construct.py
  sds_data_manager/lambda_code/SDSCode/api_lambdas/metakernel.py
Labels: SPICE

#747 I-ALiRT - Construct for Coverage Plots
  outages_test.json
  sds_data_manager/constructs/ialirt_coverage_construct.py
  sds_data_manager/lambda_code/IAlirtCode/Dockerfile.coverage
  sds_data_manager/lambda_code/IAlirtCode/ialirt_coverage.py
  sds_data_manager/utils/stackbuilder.py
  tests/infrastructure/test_ialirt_coverage_construct.py
  tests/lambda_endpoints/test_ialirt_coverage.py
Labels: I-ALiRT
