Repository IMAP-Science-Operations-Center/sds-data-manager, pull requests merged in 2025-05, with the labels that each got.

#559 Simplify Dependency API
  lambda_layer/database/requirements.txt
  lambda_layer/spice/requirements.txt
  poetry.lock
  pyproject.toml
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/batch_starter.py
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/dependency.py
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/dependency_config.csv
  sds_data_manager/lambda_code/processing/requirements.txt
  tests/lambda_endpoints/conftest.py
  tests/lambda_endpoints/test_batch_starter.py
  tests/lambda_endpoints/test_dependency_api.py
Labels: enhancement

#564 I-ALiRT - Populate l0 DB
  sds_data_manager/lambda_code/IAlirtCode/ialirt_ingest.py
  tests/lambda_endpoints/test_ialirt_ingest.py
Labels: I-ALiRT

#606 Skip /spice folder in database synchronizer
  sds_data_manager/lambda_code/SDSCode/database/synchronizer.py
Labels: bug

#617 First Pass: Querying Between db Tables
  sds_data_manager/lambda_code/SDSCode/api_lambdas/query_api.py
  tests/lambda_endpoints/test_query_api.py
Labels: Student

#632 Ultra - update dependencies
  lambda_layer/database/requirements.txt
  lambda_layer/spice/requirements.txt
  poetry.lock
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/dependency_config.csv
  sds_data_manager/lambda_code/processing/requirements.txt
Labels: Infrastructure

#635 Remove processed SQS messages.
  sds_data_manager/constructs/instrument_lambdas.py
  sds_data_manager/constructs/sqs_construct.py
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/batch_starter.py
  tests/lambda_endpoints/test_batch_starter.py
Labels: bug
