Repository IMAP-Science-Operations-Center/sds-data-manager, pull requests merged in 2025-06, with the labels that each got.

#663 Ultra spin table needed for extendedspin
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/dependency_config.csv
Labels: bug

#665 Added time kernel dependencies for Lo L1C
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/dependency_config.csv
Labels: bug

#700 I-ALiRT - S3 packets query
  sds_data_manager/constructs/ialirt_api_manager_construct.py
  sds_data_manager/lambda_code/IAlirtCode/ialirt_archive.py
  sds_data_manager/lambda_code/IAlirtCode/ialirt_log_query_api.py
  sds_data_manager/lambda_code/IAlirtCode/ialirt_packets_query_api.py
  tests/lambda_endpoints/test_ialirt_log_query_api.py
  tests/lambda_endpoints/test_ialirt_packets_query_api.py
  tests/lambda_endpoints/test_ialirt_query_api.py
Labels: I-ALiRT

#703 Ialirt sit testing
  sds_data_manager/lambda_code/IAlirtCode/ialirt_ingest.py
  tests/lambda_endpoints/test_ialirt_ingest.py
Labels: enhancement

#706 I-ALiRT - imap_processing version bump v.0.16.2
  poetry.lock
  pyproject.toml
  sds_data_manager/lambda_code/processing/requirements.txt
Labels: enhancement
