Repository IMAP-Science-Operations-Center/sds-data-manager, pull requests merged in 2025-04, with the labels that each got.

#481 Add Ancillary file handling in batch starter lambda
  sds_data_manager/constructs/dependency_finder_construct.py
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/batch_starter.py
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/dependency.py
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/indexer.py
  sds_data_manager/utils/stackbuilder.py
  tests/infrastructure/test_dependency_finder_construct.py
  tests/lambda_endpoints/conftest.py
  tests/lambda_endpoints/test_batch_starter.py
  tests/lambda_endpoints/test_dependency_api.py
Labels: Infrastructure

#497 Query parameter variable name bug in batch_starter.py
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/batch_starter.py
  tests/lambda_endpoints/test_batch_starter.py
Labels: bug

#500 I-ALiRT - root certificate
  sds_data_manager/utils/stackbuilder.py
Labels: I-ALiRT

#484 Adding Query by Ingestion Start and End Date
  sds_data_manager/lambda_code/SDSCode/api_lambdas/query_api.py
  tests/lambda_endpoints/test_query_api.py
Labels: Student

#503 1564 hi dependencies updates
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/dependency_config.csv
Labels: Infrastructure

#507 Database Bump and Protections Added
  sds_data_manager/constructs/data_bucket_construct.py
  sds_data_manager/constructs/database_construct.py
  sds_data_manager/constructs/ecr_construct.py
  sds_data_manager/utils/stackbuilder.py
  tests/infrastructure/test_data_bucket.py
  tests/infrastructure/test_database_construct.py
  tests/infrastructure/test_indexer_lambda_construct.py
  tests/infrastructure/test_sds_api_manager_construct.py
Labels: bug

#512 Fix bug in dependency api
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/batch_starter.py
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/dependency.py
  tests/lambda_endpoints/conftest.py
  tests/lambda_endpoints/test_batch_starter.py
  tests/lambda_endpoints/test_dependency_api.py
Labels: bug

#516 Bugfix: batch starter skipped files
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/batch_starter.py
  tests/lambda_endpoints/test_batch_starter.py
Labels: bug

#515 I-ALiRT - Import imap processing
  .pre-commit-config.yaml
  lambda_layer/database/requirements.txt
  poetry.lock
  pyproject.toml
  sds_data_manager/constructs/ialirt_ingest_lambda_construct.py
  sds_data_manager/lambda_code/IAlirtCode/Dockerfile
  sds_data_manager/lambda_code/IAlirtCode/ialirt_ingest.py
  sds_data_manager/lambda_code/IAlirtCode/requirements.txt
  sds_data_manager/utils/stackbuilder.py
  tests/lambda_endpoints/test_ialirt_ingest.py
Labels: I-ALiRT

#511 Return most recent upstream ancillary file with the max version number from dependency API
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/dependency.py
  tests/lambda_endpoints/conftest.py
  tests/lambda_endpoints/test_batch_starter.py
  tests/lambda_endpoints/test_dependency_api.py
Labels: enhancement

#532 I-ALiRT - CDF Cron Job
  .pre-commit-config.yaml
  lambda_layer/database/requirements.txt
  poetry.lock
  pyproject.toml
  sds_data_manager/constructs/ialirt_archive_construct.py
  sds_data_manager/constructs/ialirt_ingest_lambda_construct.py
  sds_data_manager/lambda_code/IAlirtCode/Dockerfile.archive
  sds_data_manager/lambda_code/IAlirtCode/Dockerfile.ingest
  sds_data_manager/lambda_code/IAlirtCode/ialirt_archive.py
  sds_data_manager/lambda_code/processing/requirements.txt
  sds_data_manager/utils/stackbuilder.py
  tests/infrastructure/test_ialirt_archive_construct.py
  tests/lambda_endpoints/test_ialirt_archive.py
Labels: I-ALiRT

#543 Bump imap-data-access
  lambda_layer/database/requirements.txt
  lambda_layer/spice/requirements.txt
  poetry.lock
  pyproject.toml
  sds_data_manager/lambda_code/processing/requirements.txt
Labels: bug

#501 Soft Dependency Handling
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/batch_starter.py
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/dependency.py
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/dependency_config.csv
  tests/lambda_endpoints/conftest.py
  tests/lambda_endpoints/test_batch_starter.py
  tests/lambda_endpoints/test_dependency_api.py
Labels: enhancement, Infrastructure

#502 I-ALiRT - EFS mount to lambda
  sds_data_manager/constructs/ialirt_ingest_lambda_construct.py
  sds_data_manager/utils/stackbuilder.py
Labels: I-ALiRT

#557 Fetch all upstream files for all relationship types
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/batch_starter.py
  sds_data_manager/lambda_code/SDSCode/pipeline_lambdas/dependency.py
  tests/lambda_endpoints/test_batch_starter.py
  tests/lambda_endpoints/test_dependency_api.py
Labels: enhancement

#568 I-ALiRT - Added access for opssw
  sds_data_manager/constructs/ialirt_processing_construct.py
Labels: I-ALiRT
